
variables <- tibble(
    varname = c(
        'year',
        'age',
        'gender',
        'workinghours',
        'employersec',
        'wp_location',
        'wp_nofpeople',
        'stmt_manytasks',
        'stmt_wellinformed',
        'stmt_treatedfair',
        'stmt_jobsecure',
        'stmt_physdmd',
        'stmt_mentdmd',
        'jobinsec_laidoff',
        'jobinsec_dismissed',
        'change_meaningfulness',
        'change_keptuptodate',
        'change_devopportunities',
        'change_influencestatus',
        'change_finance',
        'finance_grade'
    ),
    datatype = c(
        'integer',
        'integer',
        'categorical',
        'integer',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical',
        'categorical'
    ),
    mapping = c(
        'year',
        'ika',
        'sukup',
        'saanai',
        'toimi',
        'avi',
        'k2',
        'k21c_1',
        'k21c_4',
        'k21c_5',
        'k21c_6',
        'k21c_8',
        'k21c_9',
        'k22_1',
        'k22_2',
        'k25_1',
        'k25_4',
        'k25_6',
        'k25_7',
        'k25_8',
        'k25_9'
    ),
    label = c(
        'Year',
        'Age',
        'Gender',
        'Regular working hours per week',
        'Employer sector',
        'Location of the workplace',
        'Number of people in the workplace',
        'Too many tasks to carry out at the workplace compared to the number of employees',
        'In the workplace, people are well informed and kept up to date about things',
        'In the workplace, employees are treated fairly',
        'One can be certain that the job is secure',
        'Work is physically very demanding',
        'Work is mentally very demanding',
        'Possibility next year for being laid off for at least two weeks',
        'Possibility next year for being dismissed',
        'Change in working life in terms of meaningfulness of work',
        'Change in working life in terms of being kept up to date about the future plans of the workplace',
        "Change in working life in terms of opportunities to develop one's competence and skills at work",
        'Change in working life in terms of opportunities to influence own status and tasks at work',
        'Change in the financial situation of the workplace',
        'Grade from 0 to 10 of the financial situation of the workplace'
    )
)
